// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba.instantanea;

//
// IDL:corba/instantanea/EstadoRobotD:1.0
//
final public class EstadoRobotDHelper
{
    public static void
    insert(org.omg.CORBA.Any any, EstadoRobotD val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static EstadoRobotD
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[3];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "nombre";
            members[0].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "id";
            members[1].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_ulong);

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "IORrob";
            members[2].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            typeCode_ = orb.create_struct_tc(id(), "EstadoRobotD", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:corba/instantanea/EstadoRobotD:1.0";
    }

    public static EstadoRobotD
    read(org.omg.CORBA.portable.InputStream in)
    {
        EstadoRobotD _ob_v = new EstadoRobotD();
        _ob_v.nombre = in.read_string();
        _ob_v.id = in.read_ulong();
        _ob_v.IORrob = in.read_string();
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, EstadoRobotD val)
    {
        out.write_string(val.nombre);
        out.write_ulong(val.id);
        out.write_string(val.IORrob);
    }
}
