// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba.instantanea;

//
// IDL:corba/instantanea/EstadoRobotD:1.0
//
final public class EstadoRobotDHolder implements org.omg.CORBA.portable.Streamable
{
    public EstadoRobotD value;

    public
    EstadoRobotDHolder()
    {
    }

    public
    EstadoRobotDHolder(EstadoRobotD initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = EstadoRobotDHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        EstadoRobotDHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return EstadoRobotDHelper.type();
    }
}
