// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba.instantanea;

//
// IDL:corba/instantanea/InstantaneaD:1.0
//
final public class InstantaneaDHolder implements org.omg.CORBA.portable.Streamable
{
    public InstantaneaD value;

    public
    InstantaneaDHolder()
    {
    }

    public
    InstantaneaDHolder(InstantaneaD initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = InstantaneaDHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        InstantaneaDHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return InstantaneaDHelper.type();
    }
}
