// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba.instantanea;

//
// IDL:corba/instantanea/InstantaneaD:1.0
//
final public class InstantaneaDHelper
{
    public static void
    insert(org.omg.CORBA.Any any, InstantaneaD val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static InstantaneaD
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[1];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "estadorobs";
            members[0].type = orb.create_sequence_tc(0, EstadoRobotDHelper.type());

            typeCode_ = orb.create_struct_tc(id(), "InstantaneaD", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:corba/instantanea/InstantaneaD:1.0";
    }

    public static InstantaneaD
    read(org.omg.CORBA.portable.InputStream in)
    {
        InstantaneaD _ob_v = new InstantaneaD();
        int len0 = in.read_ulong();
        _ob_v.estadorobs = new EstadoRobotD[len0];
        for(int i0 = 0 ; i0 < len0 ; i0++)
            _ob_v.estadorobs[i0] = EstadoRobotDHelper.read(in);
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, InstantaneaD val)
    {
        int len0 = val.estadorobs.length;
        out.write_ulong(len0);
        for(int i0 = 0 ; i0 < len0 ; i0++)
            EstadoRobotDHelper.write(out, val.estadorobs[i0]);
    }
}
