// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba.instantanea;

//
// IDL:corba/instantanea/InstantaneaD:1.0
//
/***/

final public class InstantaneaD implements org.omg.CORBA.portable.IDLEntity
{
    public
    InstantaneaD()
    {
    }

    public
    InstantaneaD(EstadoRobotD[] estadorobs)
    {
        this.estadorobs = estadorobs;
    }

    public EstadoRobotD[] estadorobs;
}
