// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba;

//
// IDL:corba/Echo:1.0
//
final public class EchoHolder implements org.omg.CORBA.portable.Streamable
{
    public Echo value;

    public
    EchoHolder()
    {
    }

    public
    EchoHolder(Echo initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = EchoHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        EchoHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return EchoHelper.type();
    }
}
