// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba;

//
// IDL:corba/Echo:1.0
//
/***/

public interface Echo extends EchoOperations,
                              org.omg.CORBA.Object,
                              org.omg.CORBA.portable.IDLEntity
{
}
