// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba;

//
// IDL:corba/Echo:1.0
//
/***/

public interface EchoOperations
{
    //
    // IDL:corba/Echo/echo_:1.0
    //
    /***/

    public String
    echo_(String x);
}
