// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba.robot;

//
// IDL:corba/robot/RobotSeguidorInt:1.0
//
public class _RobotSeguidorIntStub extends org.omg.CORBA.portable.ObjectImpl
                                   implements RobotSeguidorInt
{
    private static final String[] _ob_ids_ =
    {
        "IDL:corba/robot/RobotSeguidorInt:1.0",
    };

    public String[]
    _ids()
    {
        return _ob_ids_;
    }

    final public static java.lang.Class _ob_opsClass = RobotSeguidorIntOperations.class;

    //
    // IDL:corba/robot/RobotSeguidorInt/ObtenerEstado:1.0
    //
    public void
    ObtenerEstado(corba.instantanea.EstadoRobotDHolder _ob_ah0)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("ObtenerEstado", true);
                    in = _invoke(out);
                    _ob_ah0.value = corba.instantanea.EstadoRobotDHelper.read(in);
                    return;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("ObtenerEstado", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                RobotSeguidorIntOperations _ob_self = (RobotSeguidorIntOperations)_ob_so.servant;
                try
                {
                    _ob_self.ObtenerEstado(_ob_ah0);
                    return;
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }
}
