// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba.robot;

//
// IDL:corba/robot/RobotSeguidorInt:1.0
//
/***/

public interface RobotSeguidorIntOperations
{
    //
    // IDL:corba/robot/RobotSeguidorInt/ObtenerEstado:1.0
    //
    /***/

    public void
    ObtenerEstado(corba.instantanea.EstadoRobotDHolder est);
}
