package corba;


/**
* corba/_CifradorStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/sdi/jsimo/00_basico/prj-corbacif/src/Cifrador.idl
* martes 24 de septiembre de 2013 12H31' CEST
*/

public class _CifradorStub extends org.omg.CORBA.portable.ObjectImpl implements corba.Cifrador
{

  public String cifra (String input, String clave)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cifra", true);
                $out.write_string (input);
                $out.write_string (clave);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return cifra (input, clave        );
            } finally {
                _releaseReply ($in);
            }
  } // cifra

  public String descifra (String input, String clave)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("descifra", true);
                $out.write_string (input);
                $out.write_string (clave);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return descifra (input, clave        );
            } finally {
                _releaseReply ($in);
            }
  } // descifra

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/Cifrador:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CifradorStub
