package corba;

/**
* corba/CifradorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/sdi/jsimo/00_basico/prj-corbacif/src/Cifrador.idl
* martes 24 de septiembre de 2013 12H31' CEST
*/

public final class CifradorHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.Cifrador value = null;

  public CifradorHolder ()
  {
  }

  public CifradorHolder (corba.Cifrador initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.CifradorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.CifradorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.CifradorHelper.type ();
  }

}
