package corba;


/**
* corba/CifradorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/sdi/jsimo/00_basico/prj-corbacif/src/Cifrador.idl
* martes 24 de septiembre de 2013 12H31' CEST
*/

public abstract class CifradorPOA extends org.omg.PortableServer.Servant
 implements corba.CifradorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("cifra", new java.lang.Integer (0));
    _methods.put ("descifra", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/Cifrador/cifra
       {
         String input = in.read_string ();
         String clave = in.read_string ();
         String $result = null;
         $result = this.cifra (input, clave);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // corba/Cifrador/descifra
       {
         String input = in.read_string ();
         String clave = in.read_string ();
         String $result = null;
         $result = this.descifra (input, clave);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/Cifrador:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Cifrador _this() 
  {
    return CifradorHelper.narrow(
    super._this_object());
  }

  public Cifrador _this(org.omg.CORBA.ORB orb) 
  {
    return CifradorHelper.narrow(
    super._this_object(orb));
  }


} // class CifradorPOA
