package corba;


/**
* corba/CifradorPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/sdi/jsimo/00_basico/prj-corbacif/src/Cifrador.idl
* martes 24 de septiembre de 2013 12H31' CEST
*/

public class CifradorPOATie extends CifradorPOA
{

  // Constructors

  public CifradorPOATie ( corba.CifradorOperations delegate ) {
      this._impl = delegate;
  }
  public CifradorPOATie ( corba.CifradorOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public corba.CifradorOperations _delegate() {
      return this._impl;
  }
  public void _delegate (corba.CifradorOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String cifra (String input, String clave)
  {
    return _impl.cifra(input, clave);
  } // cifra

  public String descifra (String input, String clave)
  {
    return _impl.descifra(input, clave);
  } // descifra

  private corba.CifradorOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class CifradorPOATie
