package corba;


/**
* corba/CifradorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/sdi/jsimo/00_basico/prj-corbacif/src/Cifrador.idl
* martes 24 de septiembre de 2013 12H31' CEST
*/

abstract public class CifradorHelper
{
  private static String  _id = "IDL:corba/Cifrador:1.0";

  public static void insert (org.omg.CORBA.Any a, corba.Cifrador that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba.Cifrador extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (corba.CifradorHelper.id (), "Cifrador");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba.Cifrador read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CifradorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba.Cifrador value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static corba.Cifrador narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.Cifrador)
      return (corba.Cifrador)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba._CifradorStub stub = new corba._CifradorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static corba.Cifrador unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.Cifrador)
      return (corba.Cifrador)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba._CifradorStub stub = new corba._CifradorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
