package corba;


/**
* corba/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Y:/Documents/workspace/prj-corbaecho/src/Echo.idl
* Wednesday, October 15, 2014 7:54:52 PM CEST
*/

public interface EchoOperations 
{
  String echo (String x);
} // interface EchoOperations
