// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba.camara;

//
// IDL:corba/camara/CamaraInt:1.0
//
public class _CamaraIntStub extends org.omg.CORBA.portable.ObjectImpl
                            implements CamaraInt
{
    private static final String[] _ob_ids_ =
    {
        "IDL:corba/camara/CamaraInt:1.0",
    };

    public String[]
    _ids()
    {
        return _ob_ids_;
    }

    final public static java.lang.Class _ob_opsClass = CamaraIntOperations.class;

    //
    // IDL:corba/camara/CamaraInt/SuscribirRobot:1.0
    //
    public suscripcionD
    SuscribirRobot(String _ob_a0)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("SuscribirRobot", true);
                    out.write_string(_ob_a0);
                    in = _invoke(out);
                    suscripcionD _ob_r = suscripcionDHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("SuscribirRobot", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                CamaraIntOperations _ob_self = (CamaraIntOperations)_ob_so.servant;
                try
                {
                    return _ob_self.SuscribirRobot(_ob_a0);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }
}
