// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba.camara;

//
// IDL:corba/camara/IPYPortD:1.0
//
final public class IPYPortDHolder implements org.omg.CORBA.portable.Streamable
{
    public IPYPortD value;

    public
    IPYPortDHolder()
    {
    }

    public
    IPYPortDHolder(IPYPortD initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = IPYPortDHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        IPYPortDHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return IPYPortDHelper.type();
    }
}
