// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba.camara;

//
// IDL:corba/camara/suscripcionD:1.0
//
/***/

final public class suscripcionD implements org.omg.CORBA.portable.IDLEntity
{
    public
    suscripcionD()
    {
    }

    public
    suscripcionD(int id,
                 IPYPortD iport)
    {
        this.id = id;
        this.iport = iport;
    }

    public int id;
    public IPYPortD iport;
}
