// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba.instantanea;

//
// IDL:corba/instantanea/EstadoRobotD:1.0
//
/***/

final public class EstadoRobotD implements org.omg.CORBA.portable.IDLEntity
{
    public
    EstadoRobotD()
    {
    }

    public
    EstadoRobotD(String nombre,
                 int id,
                 String IORrob)
    {
        this.nombre = nombre;
        this.id = id;
        this.IORrob = IORrob;
    }

    public String nombre;
    public int id;
    public String IORrob;
}
