// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba.camara;

//
// IDL:corba/camara/CamaraInt:1.0
//
/***/

public interface CamaraIntOperations
{
    //
    // IDL:corba/camara/CamaraInt/SuscribirRobot:1.0
    //
    /***/

    public suscripcionD
    SuscribirRobot(String IORrob);
}
