// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba.camara;

//
// IDL:corba/camara/IPYPortD:1.0
//
/***/

final public class IPYPortD implements org.omg.CORBA.portable.IDLEntity
{
    public
    IPYPortD()
    {
    }

    public
    IPYPortD(String ip,
             int port)
    {
        this.ip = ip;
        this.port = port;
    }

    public String ip;
    public int port;
}
