// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package corba.camara;

//
// IDL:corba/camara/suscripcionD:1.0
//
final public class suscripcionDHelper
{
    public static void
    insert(org.omg.CORBA.Any any, suscripcionD val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static suscripcionD
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[2];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "id";
            members[0].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_ulong);

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "iport";
            members[1].type = IPYPortDHelper.type();

            typeCode_ = orb.create_struct_tc(id(), "suscripcionD", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:corba/camara/suscripcionD:1.0";
    }

    public static suscripcionD
    read(org.omg.CORBA.portable.InputStream in)
    {
        suscripcionD _ob_v = new suscripcionD();
        _ob_v.id = in.read_ulong();
        _ob_v.iport = IPYPortDHelper.read(in);
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, suscripcionD val)
    {
        out.write_ulong(val.id);
        IPYPortDHelper.write(out, val.iport);
    }
}
