package corba;


/**
* corba/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/fraguma/workspace/prj-corba/src/Echo.idl
* jueves 16 de octubre de 2014 09H35' CEST
*/

public interface EchoOperations 
{
  String echoService (String input);
} // interface EchoOperations
